modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Ezzenix/ChatAnimation/issues"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Ezzenix"
description = '''
${description}
'''
logoFile = "${id}/icon.png"
logoBlur = false
clientSideOnly=true

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
