minecraft_version=26.1
supported_versions="26.1, 26.1.1, 26.1.2"

loader_version=0.18.5
fabric_version=0.145.1+26.1
deps.modmenu=18.0.0-alpha.8

forge_version=1.21.11-61.0.2
neoforge_version=26.1.0.1-beta
yarn_mappings_neoforge_patch=1.21+build.11
