name: Publish

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Run build with Gradle Wrapper
        run: ./gradlew build -Dbuild.release=true

      - name: Upload artifacts to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: DnNYdJsx
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 892086
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          version-type: release
          loaders: fabric